#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.bash_profile

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/chendifan/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions

